version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: app_test
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - db_test
  db_test:
    container_name: db_test
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: owner
      POSTGRES_DB: task
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/data/pg:/data/postgres